// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: LCD50_854x480_prj

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void event_inc(lv_event_t * e);
void start_event(lv_event_t * e);
void event_down(lv_event_t * e);
void stop_event(lv_event_t * e);
void event_clear(lv_event_t * e);
void event_dec(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
