// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: LCD50_854x480_prj

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Label1;
extern void ui_event_brightnessInc( lv_event_t * e);
extern lv_obj_t *ui_brightnessInc;
extern void ui_event_start( lv_event_t * e);
extern lv_obj_t *ui_start;
extern void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern void ui_event_stop( lv_event_t * e);
extern lv_obj_t *ui_stop;
extern lv_obj_t *ui_Spinner2;
extern void ui_event_clear( lv_event_t * e);
extern lv_obj_t *ui_clear;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_version;
extern lv_obj_t *ui_brightness;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_canfdID;
extern lv_obj_t *ui_ccanID;
extern lv_obj_t *ui_canFDLen;
extern lv_obj_t *ui_ccanLen;
extern lv_obj_t *ui_canFDdata;
extern lv_obj_t *ui_ccCANdata;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_frameCount;
extern lv_obj_t *ui_Label14;
extern void ui_event_brightnessDec( lv_event_t * e);
extern lv_obj_t *ui_brightnessDec;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label15;
// CUSTOM VARIABLES
extern lv_obj_t *uic_brightnessInc;
extern lv_obj_t *uic_brightness;
extern lv_obj_t *uic_canfdID;
extern lv_obj_t *uic_ccanID;
extern lv_obj_t *uic_canFDLen;
extern lv_obj_t *uic_ccanLen;
extern lv_obj_t *uic_canFDdata;
extern lv_obj_t *uic_ccCANdata;
extern lv_obj_t *uic_frameCount;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

