// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: LCD50_854x480_prj

#include "ui.h"

lv_obj_t *uic_frameCount;
lv_obj_t *uic_ccCANdata;
lv_obj_t *uic_canFDdata;
lv_obj_t *uic_ccanLen;
lv_obj_t *uic_canFDLen;
lv_obj_t *uic_ccanID;
lv_obj_t *uic_canfdID;
lv_obj_t *uic_brightness;
lv_obj_t *uic_brightnessInc;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_brightnessInc = NULL;lv_obj_t *ui_start = NULL;lv_obj_t *ui_Button3 = NULL;lv_obj_t *ui_stop = NULL;lv_obj_t *ui_Spinner2 = NULL;lv_obj_t *ui_clear = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_version = NULL;lv_obj_t *ui_brightness = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_Panel3 = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_Label11 = NULL;lv_obj_t *ui_canfdID = NULL;lv_obj_t *ui_ccanID = NULL;lv_obj_t *ui_canFDLen = NULL;lv_obj_t *ui_ccanLen = NULL;lv_obj_t *ui_canFDdata = NULL;lv_obj_t *ui_ccCANdata = NULL;lv_obj_t *ui_Label12 = NULL;lv_obj_t *ui_Label13 = NULL;lv_obj_t *ui_frameCount = NULL;lv_obj_t *ui_Label14 = NULL;lv_obj_t *ui_brightnessDec = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Label15 = NULL;
// event funtions
void ui_event_brightnessInc( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      event_inc( e );
}
}

void ui_event_start( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      start_event( e );
}
}

void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      event_down( e );
}
}

void ui_event_stop( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      stop_event( e );
}
}

void ui_event_clear( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      event_clear( e );
}
}

void ui_event_brightnessDec( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      event_dec( e );
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -21 );
lv_obj_set_y( ui_Label1, -185 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"ESP32S3 with 5\" IPS 480x854 LCD\n");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_brightnessInc = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_brightnessInc, 100);
lv_obj_set_height( ui_brightnessInc, 50);
lv_obj_set_x( ui_brightnessInc, -362 );
lv_obj_set_y( ui_brightnessInc, 185 );
lv_obj_set_align( ui_brightnessInc, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_brightnessInc, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_brightnessInc, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_start = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_start, 100);
lv_obj_set_height( ui_start, 50);
lv_obj_set_x( ui_start, 236 );
lv_obj_set_y( ui_start, 185 );
lv_obj_set_align( ui_start, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_start, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_start, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_start, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_start, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button3 = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_Button3, 100);
lv_obj_set_height( ui_Button3, 50);
lv_obj_set_x( ui_Button3, -26 );
lv_obj_set_y( ui_Button3, 185 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_stop = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_stop, 100);
lv_obj_set_height( ui_stop, 50);
lv_obj_set_x( ui_stop, 354 );
lv_obj_set_y( ui_stop, 184 );
lv_obj_set_align( ui_stop, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_stop, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_stop, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_stop, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_stop, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner2 = lv_spinner_create(ui_Screen1);
//lv_spinner_set_anim_params(ui_Spinner2, 1000, 90);
lv_obj_set_width( ui_Spinner2, 80);
lv_obj_set_height( ui_Spinner2, 80);
lv_obj_set_x( ui_Spinner2, -377 );
lv_obj_set_y( ui_Spinner2, -191 );
lv_obj_set_align( ui_Spinner2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Spinner2, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_clear = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_clear, 100);
lv_obj_set_height( ui_clear, 50);
lv_obj_set_x( ui_clear, -140 );
lv_obj_set_y( ui_clear, 185 );
lv_obj_set_align( ui_clear, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_clear, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_clear, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_clear, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_clear, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 353 );
lv_obj_set_y( ui_Label3, 185 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"STOP");

ui_version = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_version, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_version, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_version, -207 );
lv_obj_set_y( ui_version, 225 );
lv_obj_set_align( ui_version, LV_ALIGN_CENTER );
lv_label_set_text(ui_version,"LVGL version");

ui_brightness = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_brightness, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_brightness, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_brightness, -336 );
lv_obj_set_y( ui_brightness, 131 );
lv_obj_set_align( ui_brightness, LV_ALIGN_CENTER );
lv_label_set_text(ui_brightness,"Brightness");

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -366 );
lv_obj_set_y( ui_Label5, 187 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"+");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 828);
lv_obj_set_height( ui_Panel1, 94);
lv_obj_set_x( ui_Panel1, -1 );
lv_obj_set_y( ui_Panel1, -92 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -364 );
lv_obj_set_y( ui_Label4, -122 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"CAN FD (J6) :");

ui_Label7 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -391 );
lv_obj_set_y( ui_Label7, -101 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"ID : ");

ui_Label8 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -386 );
lv_obj_set_y( ui_Label8, -81 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Len : ");

ui_Panel2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel2, 828);
lv_obj_set_height( ui_Panel2, 77);
lv_obj_set_x( ui_Panel2, -1 );
lv_obj_set_y( ui_Panel2, -5 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel3, 828);
lv_obj_set_height( ui_Panel3, 67);
lv_obj_set_x( ui_Panel3, -1 );
lv_obj_set_y( ui_Panel3, 73 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -347 );
lv_obj_set_y( ui_Label9, -26 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Classic CAN (J7) : ");

ui_Label10 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -392 );
lv_obj_set_y( ui_Label10, -6 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"ID :");

ui_Label11 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -386 );
lv_obj_set_y( ui_Label11, 15 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Len :");

ui_canfdID = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_canfdID, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canfdID, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_canfdID, 55 );
lv_obj_set_y( ui_canfdID, -101 );
lv_obj_set_align( ui_canfdID, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_canfdID,"0");
lv_obj_set_style_text_align(ui_canfdID, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ccanID = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_ccanID, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ccanID, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ccanID, 53 );
lv_obj_set_y( ui_ccanID, -7 );
lv_obj_set_align( ui_ccanID, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_ccanID,"0");
lv_obj_set_style_text_align(ui_ccanID, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canFDLen = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_canFDLen, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canFDLen, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_canFDLen, 62 );
lv_obj_set_y( ui_canFDLen, -80 );
lv_obj_set_align( ui_canFDLen, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_canFDLen,"0");
lv_obj_set_style_text_align(ui_canFDLen, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ccanLen = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_ccanLen, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ccanLen, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ccanLen, 64 );
lv_obj_set_y( ui_ccanLen, 17 );
lv_obj_set_align( ui_ccanLen, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_ccanLen,"0");
lv_obj_set_style_text_align(ui_ccanLen, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canFDdata = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_canFDdata, 712);
lv_obj_set_height( ui_canFDdata, 49);
lv_obj_set_x( ui_canFDdata, 116 );
lv_obj_set_y( ui_canFDdata, -105 );
lv_obj_set_align( ui_canFDdata, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_canFDdata,"0");
lv_obj_set_style_text_align(ui_canFDdata, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ccCANdata = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_ccCANdata, 427);
lv_obj_set_height( ui_ccCANdata, 42);
lv_obj_set_x( ui_ccCANdata, 147 );
lv_obj_set_y( ui_ccCANdata, -13 );
lv_obj_set_align( ui_ccCANdata, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_ccCANdata,"0");
lv_obj_set_style_text_align(ui_ccCANdata, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, -374 );
lv_obj_set_y( ui_Label12, 60 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"Transmit");

ui_Label13 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, -356 );
lv_obj_set_y( ui_Label13, 86 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"Frame count :");

ui_frameCount = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_frameCount, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_frameCount, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_frameCount, 131 );
lv_obj_set_y( ui_frameCount, 86 );
lv_obj_set_align( ui_frameCount, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_frameCount,"0");
lv_obj_set_style_text_align(ui_frameCount, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label14 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label14, -340 );
lv_obj_set_y( ui_Label14, 226 );
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"skpang.co.uk 07/25");

ui_brightnessDec = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_brightnessDec, 100);
lv_obj_set_height( ui_brightnessDec, 50);
lv_obj_set_x( ui_brightnessDec, -254 );
lv_obj_set_y( ui_brightnessDec, 185 );
lv_obj_set_align( ui_brightnessDec, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_brightnessDec, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_brightnessDec, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -252 );
lv_obj_set_y( ui_Label6, 186 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"-");
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 236 );
lv_obj_set_y( ui_Label2, 186 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"START");

ui_Label15 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, -141 );
lv_obj_set_y( ui_Label15, 187 );
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"Clear");

lv_obj_add_event_cb(ui_brightnessInc, ui_event_brightnessInc, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_start, ui_event_start, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_stop, ui_event_stop, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_clear, ui_event_clear, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_brightnessDec, ui_event_brightnessDec, LV_EVENT_ALL, NULL);
uic_brightnessInc = ui_brightnessInc;
uic_brightness = ui_brightness;
uic_canfdID = ui_canfdID;
uic_ccanID = ui_ccanID;
uic_canFDLen = ui_canFDLen;
uic_ccanLen = ui_ccanLen;
uic_canFDdata = ui_canFDdata;
uic_ccCANdata = ui_ccCANdata;
uic_frameCount = ui_frameCount;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Label1= NULL;
uic_brightnessInc= NULL;
ui_brightnessInc= NULL;
ui_start= NULL;
ui_Button3= NULL;
ui_stop= NULL;
ui_Spinner2= NULL;
ui_clear= NULL;
ui_Label3= NULL;
ui_version= NULL;
uic_brightness= NULL;
ui_brightness= NULL;
ui_Label5= NULL;
ui_Panel1= NULL;
ui_Label4= NULL;
ui_Label7= NULL;
ui_Label8= NULL;
ui_Panel2= NULL;
ui_Panel3= NULL;
ui_Label9= NULL;
ui_Label10= NULL;
ui_Label11= NULL;
uic_canfdID= NULL;
ui_canfdID= NULL;
uic_ccanID= NULL;
ui_ccanID= NULL;
uic_canFDLen= NULL;
ui_canFDLen= NULL;
uic_ccanLen= NULL;
ui_ccanLen= NULL;
uic_canFDdata= NULL;
ui_canFDdata= NULL;
uic_ccCANdata= NULL;
ui_ccCANdata= NULL;
ui_Label12= NULL;
ui_Label13= NULL;
uic_frameCount= NULL;
ui_frameCount= NULL;
ui_Label14= NULL;
ui_brightnessDec= NULL;
ui_Label6= NULL;
ui_Label2= NULL;
ui_Label15= NULL;

}
